FROM mshub-registry.cn-zhangjiakou.cr.aliyuncs.com/modelscope-repo/agent-fabric:2025-05-26-23e278

COPY requirements.txt /home/workspace/requirements.txt
COPY . /home/workspace

WORKDIR /home/workspace/apps/agentfabric
